repos:
  - repo: local
    hooks:
      - id: hookpin
        name: sync uv additional dependencies
        language: python
        entry: hookpin
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - ruamel.yaml==0.19.1

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.15.14'
    hooks:
      - id: ruff-check
        name: ruff
        args: ['--fix']
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ['-r', '-lll']

  - repo: https://github.com/pylint-dev/pylint
    rev: v4.0.5
    hooks:
      - id: pylint
        types: [python]
        additional_dependencies:
          - pytest==9.1.1
          - ruamel.yaml==0.19.1

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        additional_dependencies:
          - ruamel.yaml==0.19.1
